manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: arunsenau                         #new entry
      url-base: https://github.com/arunsenau  #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
#    - name: nice-view-plus
#      remote: arunsenau
#      revision: main
    - name: zmk-feature-caps
      remote: arunsenau
      revision: main
  self:
    path: config
