manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dwellerau
      url-base: https://github.com/dwellerau
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-plus
      remote: dwellerau
      revision: main
    - name: zmk-caps-mod
      remote: dwellerau
      revision: main
      path: app/modules/zmk-caps-mod
  self:
    path: config
